#include "CLIEngine/core.hpp"

namespace CLIEngine {

namespace Assets {

const CLIEngine::Sprite palette{
    {
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum",
        "Lorem Ipsum"
    },
    {
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW"
    },
    {
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "XXXXXXXXXXX",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "BBBBBBBBBBB",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "GGGGGGGGGGG",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "CCCCCCCCCCC",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "RRRRRRRRRRR",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "PPPPPPPPPPP",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "OOOOOOOOOOO",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "aaaaaaaaaaa",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "AAAAAAAAAAA",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "bbbbbbbbbbb",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ggggggggggg",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "ccccccccccc",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "rrrrrrrrrrr",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "ppppppppppp",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "YYYYYYYYYYY",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW",
        "WWWWWWWWWWW"
    }
};

}

}